# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alter-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alter-iOS
  pod 'SwiftLint'

  target 'Alter-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Alter-macOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alter-macOS
  pod 'SwiftLint'

  target 'Alter-macOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
