env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.3
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -project Development/Alter.xcodeproj -scheme Alter-macOS -configuration Release ENABLE_TESTABILITY=YES | bundle exec xcpretty -c
        - xcodebuild build-for-testing test-without-building -project Development/Alter.xcodeproj -scheme Alter-iOS -configuration Release -sdk iphonesimulator -destination "name=iPhone 7" ENABLE_TESTABILITY=YES | bundle exec xcpretty -c
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      language: generic
      osx_image: xcode8.3
      script:
        - swift build
        - swift test
      env:
        - JOB=SWIFTPM_DARWIN
    # - os: linux
    #   language: generic
    #   sudo: required
    #   dist: trusty
    #   before_install:
    #     - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    #   script:
    #     - swift build
    #     - swift test
    #   env:
    #     - JOB=SWIFTPM_LINUX

notifications:
  email: false
